module.exports = {
  fakeNames: [
    "Fatuous_Gonzo",
    "Billingsgate_Gastromancy",
    "Godwottery_Cockalorum",
    "Crapulence_Lollygag",
    "Snool_Snool",
    "Smellfungus_Slangwhanger",
    "Bowyang_Nincompoop",
    "Yahoo_Fard",
    "Gobemouche_Skullduggery",
    "Cockalorum_Mugwump",
    "Gaberlunzie_Catercornered",
    "Folderol_Collop",
    "Formication_Catercornered",
    "Maverick_Kerfuffle",
    "Pettifogger_Gastromancy",
    "Maverick_Maverick",
    "Gaberlunzie_Pandiculation",
    "Godwottery_Boustrophedon",
    "Borborygm_Sialoquent",
    "Flummox_Blunderbuss",
    "Donnybrook_Canoodle",
    "Gardyloo!_Furphy",
    "Argle-bargle_Flummox",
    "Kerfuffle_Gonzo",
    "Firkin_Allegator",
    "Skullduggery_Gaberlunzie",
    "Snollygoster_Quean",
    "Argle-bargle_Allegator",
    "Gazump_Unremacadamized",
    "Discombobulate_Maverick",
    "Widdershins_Lagopodous",
    "Shenanigan_Fatuous",
    "Collywobbles_Maverick",
    "Borborygm_Hemidemisemiquaver",
    "Rambunctious_Troglodyte",
    "Eructation_Fartlek",
    "Hobbledehoy_Panjandrum",
    "Batrachomyomachy_Fuddy-duddy",
    "Goombah_Quean",
    "Rigmarole_Firkin",
    "Ornery_Batrachomyomachy",
    "Crudivore_Firkin",
    "Tatterdemalion_Lollygag",
    "Canoodle_Lickety-split",
    "Gobemouche_Codswallop",
    "Allegator_Cockamamie",
    "Widdershins_Collop",
    "Malarkey_Codswallop",
    "Shenanigan_Discombobulate",
    "Smellfungus_Gobemouche",
    "Ecdysiast_Comeuppance",
    "Anencephalous_Slangwhanger",
    "Mugwump_Folderol",
    "Boustrophedon_Collop",
    "Vomitory_Comeuppance",
    "Gongoozle_Argle-bargle",
    "Gobemouche_Callipygian",
    "Allegator_Slangwhanger",
    "Crudivore_Turdiform",
    "Kerfuffle_Bowyang",
    "Cockamamie_Vomitory",
    "Anencephalous_Gazump",
    "Oocephalus_Rambunctious",
    "Oocephalus_Hootenanny",
    "Cockamamie_Filibuster",
    "Oocephalus_Callipygian",
    "Malarkey_Turdiform",
    "Bloviate_Mollycoddle",
    "Billingsgate_Abibliophobia",
    "Absquatulate_Unremacadamized",
    "Widdershins_Malarkey",
    "Bloviate_Gaberlunzie",
    "Billingsgate_Boustrophedon",
    "Donnybrook_Ranivorous",
    "Formication_Widdershins",
    "Rambunctious_Lollygag",
    "Batrachomyomachy_Snool",
    "Codswallop_Discombobulate",
    "La-di-da_Lickspittle",
    "Namby-pamby_Jackanapes",
    "Flummox_Slangwhanger",
    "Gongoozle_Doozy",
    "Gaberlunzie_Hootenanny",
    "Gonzo_Furbelow",
    "Furbelow_Klutz",
    "Lickspittle_Lickety-split",
    "Namby-pamby_Argle-bargle",
    "Pettifogger_Dudgeon",
    "Hocus-pocus_Oocephalus",
    "Mollycoddle_Fard",
    "Panjandrum_Bowyang",
    "Firkin_Crudivore",
    "Hemidemisemiquaver_Shenanigan",
    "Collywobbles_Dudgeon",
    "Jackanapes_Fuddy-duddy",
    "Quean_Lickspittle",
    "Ranivorous_Ornery",
    "Cockalorum_Furphy",
    "Gaberlunzie_Hocus-pocus",
    "Ecdysiast_Collop"
  ],
  fakeAbouts:
    ["VHS beard typewriter, kickstarter put a bird on it umami pitchfork whatever you probably haven't heard of them master cleanse seitan vegan williamsburg iPhone", "Lyft shoreditch echo park VHS kombucha bushwick franzen af skateboard paleo raclette bespoke wolf microdosing", "Sriracha coloring book vice wayfarers hell of farm-to-table skateboard single-origin coffee ramps gentrify la croix stumptown, photo booth gluten-free chicharrones", "Viral gluten-free air plant mustache migas semiotics, cronut echo park live-edge trust fund venmo", "Quinoa mixtape lyft pork belly, tousled godard heirloom cornhole offal subway tile single-origin coffee literally fam", "Wayfarers dreamcatcher aesthetic, thundercats church-key yuccie hammock cliche 90's af squid williamsburg hoodie salvia kickstarter", "Art party cloud bread occupy palo santo shaman, next level twee cornhole whatever lomo four dollar toast", "Skateboard schlitz taiyaki plaid freegan beard, poke umami vegan taxidermy franzen", "Tote bag gochujang ethical poke four loko blog cornhole small batch farm-to-table", "8-bit small batch ugh church-key lo-fi green juice, lomo vape XOXO chambray", "Heirloom pork belly kogi unicorn", "Literally gastropub air plant, live-edge cardigan gochujang thundercats vice", "Squid pork belly drinking vinegar semiotics banjo", "Enamel pin iPhone synth dreamcatcher four loko tumeric sartorial 3 wolf moon", "Keytar mustache yr etsy, schlitz poutine flannel", "Pop-up squid helvetica try-hard paleo authentic hoodie selvage post-ironic", "Roof party yuccie kitsch trust fund tumblr everyday carry, cliche master cleanse kickstarter air plant", "Flannel venmo la croix tumblr edison bulb post-ironic single-origin coffee art party portland williamsburg pug", "Cronut paleo four loko tumblr, blue bottle raclette yuccie bushwick seitan marfa pop-up kogi narwhal vaporware", "Truffaut fam offal raw denim, mixtape helvetica crucifix you probably haven't heard of them wayfarers knausgaard woke shoreditch fixie", "Tote bag sriracha poutine health goth, migas tousled literally 8-bit hoodie", "Lyft shaman celiac migas keffiyeh iPhone, four loko food truck kogi vaporware lumbersexual", "Man bun prism portland flexitarian", "Tbh jianbing butcher, art party tofu 90's next level kinfolk portland polaroid fam", "Photo booth affogato meh PBR&B", "YOLO photo booth four loko chambray synth organic tofu", "Art party DIY normcore echo park pinterest retro iPhone XOXO", "Unicorn wayfarers tilde adaptogen actually mumblecore franzen chartreuse hammock bushwick copper mug direct trade yr", "Air plant squid jianbing, taxidermy cold-pressed crucifix kickstarter direct trade green juice bitters", "Brooklyn williamsburg flannel deep v, distillery viral banjo single-origin coffee gastropub", "Pickled listicle deep v swag, post-ironic vinyl narwhal cloud bread af chia", "Tousled woke neutra, 8-bit succulents food truck tbh four loko hexagon", "Man bun venmo pok pok, ennui live-edge direct trade yr", "Waistcoat readymade neutra, heirloom pok pok iPhone taxidermy paleo kinfolk", "Tilde slow-carb typewriter distillery", "Cliche mustache vegan, biodiesel lyft succulents thundercats hexagon squid skateboard", "Hammock PBR&B microdosing, VHS lomo narwhal craft beer taxidermy fashion axe humblebrag", "Skateboard tilde occupy sustainable", "Humblebrag fam offal jianbing synth fashion axe, edison bulb put a bird on it chillwave slow-carb retro semiotics", "Edison bulb microdosing blog retro", "Bushwick gochujang typewriter bitters", "3 wolf moon ethical bushwick, forage hashtag PBR&B copper mug lomo live-edge", "Lumbersexual twee listicle pickled chartreuse venmo flannel skateboard cray squid crucifix marfa 8-bit kogi tattooed", "Viral intelligentsia messenger bag migas, pickled meggings cold-pressed tattooed", "Put a bird on it readymade locavore beard tattooed XOXO normcore yuccie synth taiyaki brooklyn copper mug", "Typewriter put a bird on it 8-bit four dollar toast", "Celiac pork belly pug street art knausgaard ramps shaman tote bag put a bird on it church-key", "Literally food truck vexillologist hot chicken chambray artisan", "Slow-carb vice taxidermy, ethical vape squid la croix photo booth celiac shoreditch af pour-over dreamcatcher", "Ugh twee swag neutra microdosing live-edge 8-bit farm-to-table pinterest", "Retro vape shaman vexillologist", "Cray tbh ramps stumptown portland pour-over, migas paleo unicorn seitan crucifix schlitz", "Freegan pitchfork vegan sartorial gentrify plaid cray migas leggings pinterest man bun cornhole pork belly next level ennui", "Pabst neutra vaporware edison bulb semiotics tumeric twee kickstarter", "Lumbersexual tousled semiotics waistcoat butcher pickled edison bulb 8-bit", "Thundercats wolf pitchfork offal occupy leggings fam affogato franzen hashtag ugh cred viral iceland put a bird on it", "Hella kogi chartreuse iceland godard beard single-origin coffee", "Flexitarian listicle food truck normcore, blue bottle hoodie mlkshk tumeric iPhone DIY adaptogen", "Biodiesel pickled keffiyeh 8-bit, pour-over pok pok fixie cred", "Raclette subway tile kale chips marfa semiotics etsy leggings", "Art party vaporware kickstarter fashion axe, palo santo street art pok pok sustainable farm-to-table echo park wolf pabst man bun flexitarian", "Fingerstache distillery hot chicken tote bag, coloring book air plant mustache master cleanse chambray flexitarian aesthetic freegan cold-pressed lumbersexual farm-to-table", "Trust fund microdosing tilde, tbh plaid blue bottle austin craft beer dreamcatcher readymade", "Adaptogen hashtag PBR&B health goth distillery squid", "Hexagon sriracha vice, tote bag fam jianbing fashion axe gastropub cornhole austin brunch", "Pork belly you probably haven't heard of them slow-carb, keytar gluten-free intelligentsia tilde pickled 3 wolf moon DIY adaptogen succulents blue bottle", "Pinterest cold-pressed farm-to-table yr coloring book polaroid seitan", "Pabst ramps PBR&B sustainable", "Artisan kinfolk chia austin kale chips green juice portland la croix poke woke", "Pok pok tousled bushwick, mlkshk 90's offal shoreditch actually health goth mumblecore craft beer paleo umami la croix sustainable", "Truffaut yr photo booth tumeric, forage pitchfork meditation pug keytar deep v disrupt crucifix pour-over kickstarter", "Unicorn lumbersexual umami pour-over cloud bread taiyaki, drinking vinegar kogi occupy lomo offal man bun chartreuse", "Flannel humblebrag vape fashion axe cray fanny pack try-hard shaman hammock palo santo whatever put a bird on it venmo", "Small batch coloring book pop-up stumptown, fam live-edge chambray ramps leggings yuccie", "Drinking vinegar trust fund small batch kombucha listicle", "Truffaut biodiesel 8-bit shoreditch, bushwick taiyaki deep v ethical gochujang tacos YOLO adaptogen", "Thundercats gluten-free pop-up, vegan dreamcatcher art party blog locavore VHS", "Fam poutine sriracha, kale chips biodiesel bicycle rights adaptogen tacos craft beer chartreuse", "Tbh tattooed salvia, cliche four dollar toast pug chicharrones jean shorts", "Actually poutine cornhole, mixtape gentrify PBR&B direct trade bicycle rights enamel pin stumptown", "Beard iceland freegan drinking vinegar vice", "Unicorn meh mixtape readymade cardigan brunch, chambray truffaut vaporware", "Celiac twee taxidermy, cred distillery pug iceland wayfarers paleo fam VHS pour-over pork belly snackwave", "Iceland shoreditch roof party, mumblecore taxidermy pork belly poke man braid freegan adaptogen", "Chia paleo street art 8-bit literally", "Bitters air plant thundercats next level listicle", "Biodiesel umami portland brunch gluten-free", "Farm-to-table single-origin coffee woke, adaptogen tumblr marfa bicycle rights +1 migas everyday carry meh church-key subway tile chartreuse pork belly", "Tumeric tofu flannel street art asymmetrical, everyday carry trust fund gentrify PBR&B", "Biodiesel bespoke before they sold out prism knausgaard", "Shaman pitchfork microdosing, dreamcatcher af ramps master cleanse bespoke artisan bicycle rights vinyl fanny pack", "Drinking vinegar scenester you probably haven't heard of them marfa", "Kogi truffaut pinterest irony normcore cold-pressed occupy", "Pabst brooklyn narwhal truffaut everyday carry poke mixtape VHS shaman aesthetic succulents quinoa YOLO", "Skateboard aesthetic fanny pack, brunch truffaut taiyaki +1 ennui cred helvetica master cleanse tacos tbh biodiesel", "Single-origin coffee health goth plaid polaroid", "Venmo tofu pinterest copper mug", "Cloud bread gastropub neutra godard jean shorts blog man braid austin", "Brunch chartreuse jean shorts roof party crucifix shaman cornhole af adaptogen four dollar toast swag cray", "Church-key ramps poutine, seitan truffaut craft beer heirloom woke retro austin portland palo santo glossier pickled", "Pok pok succulents vape vegan, la croix raw denim fashion axe thundercats activated charcoal adaptogen distillery lo-fi artisan brooklyn jianbing", "+1 truffaut church-key shaman, unicorn chartreuse art party kickstarter woke vinyl craft beer freegan vape", "8-bit cred mustache XOXO ramps", "DIY etsy vegan letterpress salvia", "Taiyaki chia squid schlitz roof party pickled slow-carb copper mug literally bespoke humblebrag hammock", "Mlkshk authentic beard, photo booth offal cloud bread brunch cronut kogi franzen tattooed", "Chia polaroid celiac kogi echo park twee", "Blog banjo gastropub YOLO kale chips pork belly church-key farm-to-table scenester cronut small batch pug lumbersexual roof party yr", "Gluten-free migas everyday carry roof party organic subway tile iPhone", "Pork belly synth meh iPhone listicle", "Letterpress VHS marfa jianbing whatever, crucifix quinoa tofu roof party mustache", "Art party gochujang tumeric skateboard, polaroid tousled dreamcatcher waistcoat pinterest schlitz mumblecore biodiesel mixtape paleo pop-up", "Bitters iPhone pok pok, master cleanse vegan food truck locavore skateboard blue bottle cray retro bushwick", "Trust fund skateboard VHS tattooed organic, squid plaid blue bottle raw denim letterpress cardigan keffiyeh lomo", "Coloring book brooklyn hexagon direct trade banjo, lomo ethical polaroid pabst craft beer chambray lumbersexual butcher affogato", "Tbh gastropub glossier sartorial jean shorts tacos", "8-bit synth iPhone vice hella", "Forage quinoa irony shoreditch tumblr next level direct trade distillery venmo meggings", "Green juice small batch flannel, offal seitan vegan williamsburg kitsch", "Blog try-hard tilde literally leggings readymade neutra kale chips authentic skateboard fixie knausgaard", "Food truck health goth helvetica YOLO, pork belly squid bespoke cliche schlitz bushwick taxidermy", "Butcher pour-over intelligentsia skateboard kickstarter fingerstache pop-up craft beer raclette", "Pickled shabby chic 90's cloud bread waistcoat distillery tofu banh mi green juice four loko four dollar toast pinterest enamel pin", "Health goth microdosing lo-fi iPhone church-key locavore hell of, ramps glossier banh mi", "Single-origin coffee 3 wolf moon paleo, scenester pug banh mi beard quinoa cred fingerstache kitsch", "Migas brooklyn bitters keytar cardigan vaporware mustache kickstarter glossier", "Heirloom flexitarian raw denim single-origin coffee glossier leggings kickstarter thundercats portland shoreditch godard woke shabby chic chambray waistcoat", "Health goth typewriter woke, cray la croix gluten-free mlkshk next level swag fixie raw denim gentrify", "Cray gochujang hammock hell of church-key glossier", "Vaporware migas four dollar toast, hell of banh mi celiac ethical kale chips", "Butcher meditation letterpress, subway tile woke gentrify knausgaard fashion axe air plant actually", "Church-key aesthetic man braid roof party", "Kombucha hot chicken skateboard cornhole direct trade bitters everyday carry single-origin coffee master cleanse kale chips live-edge letterpress tote bag readymade", "Bitters waistcoat PBR&B, actually master cleanse knausgaard adaptogen helvetica try-hard hella beard mustache taxidermy", "Pour-over readymade palo santo street art, jianbing irony jean shorts pork belly aesthetic bushwick seitan af neutra man bun farm-to-table", "Freegan viral knausgaard af jean shorts prism trust fund seitan austin salvia art party", "Biodiesel craft beer paleo, ethical photo booth iceland four loko quinoa raw denim food truck pour-over", "Hashtag messenger bag crucifix, mumblecore hexagon pabst fashion axe butcher marfa tumblr mlkshk", "Plaid subway tile cold-pressed, pitchfork sartorial cardigan cliche chia taxidermy squid", "Kinfolk mlkshk biodiesel fam trust fund, cornhole paleo readymade pickled swag", "Chartreuse ennui retro heirloom yr iceland PBR&B, etsy polaroid kogi", "Taxidermy bitters four loko cliche you probably haven't heard of them deep v authentic marfa crucifix scenester live-edge pop-up keytar ramps", "Art party vaporware health goth taiyaki lyft sustainable fashion axe everyday carry, 90's kinfolk", "Enamel pin irony lumbersexual jianbing", "Cray wolf meditation deep v locavore stumptown tbh jean shorts tofu actually marfa food truck snackwave cred", "Dreamcatcher post-ironic fam brunch gentrify glossier activated charcoal direct trade subway tile", "Taxidermy forage af williamsburg, salvia cronut hell of pitchfork adaptogen messenger bag", "Thundercats woke 3 wolf moon subway tile authentic", "Vape chambray vegan, beard ugh fanny pack jean shorts occupy kinfolk venmo freegan cornhole butcher", "Echo park pitchfork sustainable poutine, cold-pressed plaid mustache wayfarers", "Etsy locavore cronut pug", "Hella mumblecore readymade semiotics, salvia keytar artisan cornhole VHS", "Lomo typewriter man braid marfa woke", "Bicycle rights artisan forage chartreuse, echo park street art whatever cornhole jean shorts skateboard heirloom", "Tacos retro kombucha quinoa meggings vexillologist", "Craft beer deep v semiotics lo-fi slow-carb stumptown, kitsch af hexagon mumblecore", "Typewriter brooklyn kombucha VHS", "Next level knausgaard master cleanse, 8-bit cornhole tumeric pickled etsy gochujang selfies vice distillery readymade jean shorts meditation", "Narwhal tote bag godard, craft beer bicycle rights unicorn normcore activated charcoal vegan truffaut", "Synth vexillologist microdosing four dollar toast before they sold out fanny pack ennui hella gastropub shabby chic vice ethical", "Vegan offal green juice, chia etsy cold-pressed vice", "Cronut shabby chic chambray poutine, crucifix paleo dreamcatcher selvage unicorn air plant", "Roof party deep v plaid beard humblebrag selvage", "Bespoke retro roof party, wayfarers bicycle rights you probably haven't heard of them godard yuccie pork belly", "Four loko wayfarers pour-over, lo-fi XOXO four dollar toast art party ethical marfa twee", "Hammock copper mug tofu heirloom artisan stumptown yuccie", "Hell of lyft direct trade art party leggings", "Authentic mumblecore twee etsy live-edge air plant", "Salvia blue bottle bespoke pour-over try-hard", "Blue bottle shabby chic microdosing single-origin coffee adaptogen tattooed iceland listicle", "Health goth cronut truffaut vinyl celiac direct trade cliche synth glossier cardigan lomo venmo vape", "Raclette gochujang kombucha waistcoat, chambray glossier viral", "Fingerstache polaroid freegan truffaut, authentic echo park chartreuse biodiesel master cleanse live-edge", "Hammock af slow-carb raw denim", "Microdosing swag put a bird on it, try-hard raclette plaid gentrify distillery", "Hoodie locavore pok pok ethical", "Organic schlitz deep v crucifix", "Hammock taxidermy biodiesel craft beer salvia affogato enamel pin church-key ennui bushwick", "Photo booth chambray stumptown, succulents +1 pok pok direct trade before they sold out locavore umami helvetica mixtape 90's vexillologist", "Flannel vexillologist try-hard sustainable unicorn snackwave crucifix microdosing adaptogen", "Venmo affogato shoreditch, flannel schlitz tacos viral 3 wolf moon snackwave air plant blog vaporware VHS chillwave ethical", "Hot chicken disrupt brooklyn, gentrify vape green juice kickstarter master cleanse ethical live-edge knausgaard wolf flexitarian pug palo santo", "Migas umami lyft franzen squid locavore", "Meggings portland squid venmo prism blue bottle etsy food truck chia enamel pin pok pok XOXO snackwave gluten-free", "Gluten-free kombucha seitan before they sold out affogato", "Helvetica man bun tofu heirloom stumptown single-origin coffee, vice sartorial hexagon pinterest pok pok butcher coloring book sriracha", "Banjo iceland cronut, vinyl taiyaki freegan sartorial", "Four loko man braid single-origin coffee umami art party, aesthetic put a bird on it", "Distillery cliche chartreuse messenger bag cold-pressed prism swag neutra", "Lomo kogi distillery, kinfolk messenger bag tattooed knausgaard swag bushwick", "Gastropub art party schlitz dreamcatcher food truck", "Crucifix 3 wolf moon selfies blue bottle vaporware adaptogen poke farm-to-table keytar authentic pug echo park", "Vinyl sustainable gluten-free, selvage pok pok poutine everyday carry narwhal gentrify pork belly +1 vexillologist", "Whatever bespoke raclette ramps, waistcoat glossier XOXO mixtape lomo stumptown typewriter 8-bit subway tile", "Direct trade gochujang hoodie meh ennui godard quinoa meditation pabst", "Pitchfork gastropub beard palo santo semiotics succulents", "Quinoa glossier gochujang portland cred yr raclette", "Actually gochujang poke, quinoa sartorial banh mi street art disrupt meh chambray migas freegan", "Copper mug vape put a bird on it, palo santo taiyaki chicharrones four loko gochujang PBR&B try-hard pop-up slow-carb microdosing", "Mlkshk activated charcoal schlitz VHS."],
  fakeSongs: [
    "Cone BBQ",
    "Nuclear Book",
    "BBQ Breakfast",
    "Boat Dog",
    "Trees Laptop",
    "Shelf BBQ",
    "Towel Nuclear",
    "Nuclear Body",
    "Fusion Flowers",
    "Ice cream Allergies",
    "Body Flowers",
    "Male Robot",
    "Plus Sink",
    "Toilet Dog",
    "Toilet Prints",
    "Whale Leash",
    "Shoes Urine",
    "Plants Printer",
    "Ring Book",
    "Solar Post office",
    "Dislike Boat",
    "Hnads Book",
    "Rollers Towel",
    "Fusion Body",
    "Body Android",
    "Android Fence",
    "Kitty Towel",
    "Shelf Laptop",
    "Plus Robot",
    "Floppy Disk Soap",
    "Puppy Toilet",
    "Horse YouTube",
    "Poop Fusion",
    "Monster Monster",
    "Comics Kitty",
    "Body System",
    "Solar Towel",
    "Sink Crab",
    "Poop Drugs",
    "Shelf Crab",
    "YouTube Printer",
    "Post office Leash",
    "Shoes Prints",
    "Post office Laptop",
    "Trees Solar",
    "Fusion Allergies",
    "Toolbox Bird",
    "Cone Comics",
    "Soda Shoe",
    "Rollers Leash",
    "Breakfast Bird",
    "Breakfast Crab",
    "Fence Water",
    "Shoes YouTube",
    "Websites Shelf",
    "Book Comics",
    "Soda Body",
    "Cone Allergies",
    "YouTube Rollers",
    "Ice cream cone Monster",
    "Body System",
    "Running Urine",
    "Shower Hnads",
    "Cat Cone",
    "Whale Laptop",
    "Water Toolbox",
    "Bird Video games",
    "Running Sink",
    "Nuclear Water",
    "Sink Flowers",
    "Fusion Elevator",
    "Toolbox Website",
    "Bird Allergies",
    "Male Water",
    "Puppy Ring",
    "Puppy YouTube",
    "Trees Urine",
    "Dislike Soda",
    "Fence Solar",
    "YouTube Plants",
    "Puppy Mail",
    "BBQ Clock",
    "Plus Rollers",
    "Floppy Disk Kitty",
    "Dog Floppy Disk",
    "Horse Video games",
    "Plus Towel",
    "Puppy Shoes",
    "Post office Dog",
    "Bird Clock",
    "Laptop Boat",
    "Cone Post office",
    "Settings Boat",
    "Cat Settings",
    "Nuclear System",
    "Ice cream cone Soap",
    "Mail Elevator",
    "Ice cream System",
    "Cat Bird",
    "Laptop Fusion"
  ],
  album: [
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/61fCRGMOASL._SY355_.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/71b30e1GGML._SL1071_.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/ABBA-Album-Covers-16.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/ABBA-Album-Covers-6.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/ABBA_-_The_Album_(Polar).jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/Hits-Collection-CD2-cover.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/Mamma_Mia_Intermezzo_No_1.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/Mamma_Mia_Intermezzo_No_1.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/R-3365228-1505192441-2722.jpeg.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/R-465186-1155759954.jpeg.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/a7942dc139ad732d2fa2c8c0e58890fd.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/download.jpeg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/images.jpeg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/maxresdefault.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/s-l300.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/unnamed.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/1200x1200bb.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/63a3f2bbaf7d4aa10ef8849d931591a9.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/63a3f2bbaf7d4aa10ef8849d931591a9.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/abba-mamma_mia_s_19.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/ABBAKnowingMeKnowingYouHappyHawaiiA.jpg'
  ],

  profile: [
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/61fCRGMOASL._SY355_.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/71b30e1GGML._SL1071_.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/ABBA-Album-Covers-16.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/ABBA-Album-Covers-6.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/ABBA_-_The_Album_(Polar).jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/Hits-Collection-CD2-cover.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/Mamma_Mia_Intermezzo_No_1.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/Mamma_Mia_Intermezzo_No_1.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/R-3365228-1505192441-2722.jpeg.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/R-465186-1155759954.jpeg.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/a7942dc139ad732d2fa2c8c0e58890fd.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/download.jpeg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/images.jpeg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/maxresdefault.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/s-l300.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/unnamed.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/1200x1200bb.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/63a3f2bbaf7d4aa10ef8849d931591a9.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/63a3f2bbaf7d4aa10ef8849d931591a9.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/abba-mamma_mia_s_19.jpg',
    'https://fec-sidebar-album-art.s3.amazonaws.com/abba/ABBAKnowingMeKnowingYouHappyHawaiiA.jpg'
  ]

};